Try wide-char-named libraries as base
Linux builds failed while linking the internal tests with
  ncurses.c:(.text.show_wbox_chars+0x92): undefined reference to `_nc_wacs'
No idea why that symbol is missing...

Signed-off-by: Marcel Bargull <marcel.bargull@udo.edu>